# Bun configuration for the YouTube Outlier Discovery Tool server

[install]
# Install configuration
cache = "node_modules/.cache/bun"
exact = false
auto = "fallback"

# Install optional dependencies
optional = true

[test]
# Test configuration
timeout = 60000

# Coverage configuration
coverage = true
coverageThreshold = 80

[run]
# Runtime configuration
silent = false

[build]
# Build configuration - mainly for TypeScript transpilation
target = "bun"
format = "esm"
minify = false
splitting = false